### ISSUE TITLE
Error when tyring to call lsp-javacomp-enable

### ISSUE THREAD

**Issue by vkazanov** [tigersoldier/lsp-javacomp#4]
I get the following error when trying to enable the package. 

`Autoloading file /home/vladimirkazanov/.emacs.d/elpa/lsp-javacomp-20181211.204/lsp-javacomp.el failed to define function lsp-javacomp-enable`

**Comment by tigersoldier** [comment]
Hi, `lsp-mode` had a breaking change and no longer generates `lsp-javacomp-enable`. I just updated the code to define an alias for it. Should be working again if you update to the latest version (might need to wait an hour or two for MELPA).

I recommend stop using `lsp-javacomp-enable` and just call `lsp` instead. I've updated the README for the instructions.
