### ISSUE TITLE
Lots of "Error running timer: (wrong-type-argument syntax-table-p t)" errors when run with company-mode

### ISSUE THREAD

**Issue by vkazanov** [tigersoldier/lsp-javacomp#5]
Thanks for quick response last time!

Now I get a lot of errors with the following trace:

Debugger entered--Lisp error: (wrong-type-argument syntax-table-p t)
  set-syntax-table(t)
  (progn (set-syntax-table syntax-table) (bounds-of-thing-at-point-1 thing))
  (unwind-protect (progn (set-syntax-table syntax-table) (bounds-of-thing-at-point-1 thing)) (set-syntax-table buffer-syntax))
  (let ((buffer-syntax (syntax-table))) (unwind-protect (progn (set-syntax-table syntax-table) (bounds-of-thing-at-point-1 thing)) (set-syntax-table buffer-syntax)))
  (if syntax-table (let ((buffer-syntax (syntax-table))) (unwind-protect (progn (set-syntax-table syntax-table) (bounds-of-thing-at-point-1 thing)) (set-syntax-table buffer-syntax))) (bounds-of-thing-at-point-1 thing))
  bounds-of-thing-at-point(symbol t)
  (let ((bounds (bounds-of-thing-at-point thing syntax-table))) (and bounds (buffer-substring (car bounds) (cdr bounds))))
  (if (get thing 'thing-at-point) (let ((opoint (point))) (prog1 (funcall (get thing 'thing-at-point)) (constrain-to-field nil opoint))) (let ((bounds (bounds-of-thing-at-point thing syntax-table))) (and bounds (buffer-substring (car bounds) (cdr bounds)))))
  thing-at-point(symbol t)
  lsp-ui-sideline--run()
  #f(compiled-function () #<bytecode 0x46359c5>)()
  apply(#f(compiled-function () #<bytecode 0x46359c5>) nil)
  timer-event-handler([t 0 0 200000 nil #f(compiled-function () #<bytecode 0x46359c5>) nil idle 0])

I set up things the way it's described in the readme, and use Emacs 26.1 on Ubuntu 18.04.

**Comment by tigersoldier** [comment]
Looks like it's unrelated to JavaComp. This error is thrown from `sp-ui-sideline` calling `thing-at-point`.

Please make sure you don't have any package overriding `thing-at-point`. Your version in the stack trace is different from mine. Here is what this function looks like from my Emacs 26.1:

```elisp
;;;###autoload
(defun thing-at-point (thing &optional no-properties)
  "Return the THING at point.
THING should be a symbol specifying a type of syntactic entity.
Possibilities include `symbol', `list', `sexp', `defun',
`filename', `url', `email', `word', `sentence', `whitespace',
`line', `number', and `page'.

When the optional argument NO-PROPERTIES is non-nil,
strip text properties from the return value.

See the file `thingatpt.el' for documentation on how to define
a symbol as a valid THING."
  (let ((text
         (if (get thing 'thing-at-point)
             (funcall (get thing 'thing-at-point))
           (let ((bounds (bounds-of-thing-at-point thing)))
             (when bounds
               (buffer-substring (car bounds) (cdr bounds)))))))
    (when (and text no-properties (sequencep text))
      (set-text-properties 0 (length text) nil text))
    text))
```

**Comment by vkazanov** [comment]
Thanks you! I'll check and either close the ticket if it's not related to JavaComp or expand on this one if it turns out something is wrong.

BTW. There's extra quote in the README use-package setup example (`(require 'lsp-javacomp')`, notice the tailing quote).

**Comment by vkazanov** [comment]
Thanks you so much! I have a really big config, which made through multiple emacs versions. It turns out I had a tweaked `thing-at-point` implementation which overrided the bundled one.

Now things really do work as intended!
